# -*- coding: utf-8 -*-
"""Ian - Spotify Recommender Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14EpT_j6q7Re6GxqsoIcTE1LL0VcYouVR
"""

# Setting up data, data frame, pandas, numpy, file directory.

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

# path = "G:\My Drive\Colab Notebooks\Files"
df_songs = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/spotify_songs.csv')

df_songs = df_songs.drop(['title', 'type', 'Unnamed: 0', 'uri', 'track_href', 'analysis_url'], axis= 1)

df_songs = df_songs.dropna()

# What's your size?

print(df_songs.shape)

# No need for train_test split since its unsupervised learning
# Use KNN to find nearest song, and recommend this song

from sklearn.neighbors import NearestNeighbors # Recommender system
from sklearn.preprocessing import StandardScaler # Scaling data, avoid one feature domination

# Preprocessing the data:

# Identification, change if uri is needed
id_col = 'id'
name_col = 'song_name'

# artist_col =  for future usage? artist info is not included in the sheet

Track_id   = id_col
Song_name = name_col
print(f"ID: {Track_id}, Song name: {Song_name}")

# features of the songs using list comprehension
features = ['danceability','energy','key','loudness','mode','speechiness',
    'acousticness','instrumentalness','liveness','valence','tempo','duration_ms'
    , 'time_signature']

feature_cols = [c for c in features if c in df_songs.columns]

# Dropping the duplicates by name
df_songs = df_songs.drop_duplicates().reset_index(drop=True)
# Dropping the duplicates by id
df_songs = df_songs.drop_duplicates(subset=[Track_id], keep='first').reset_index(drop=True)


# Scaling the data
scaler = StandardScaler()
X = df_songs[feature_cols]
X_scaled = scaler.fit_transform(X)

# Print out scaled data and check
X_scaled

# The recommender will give human readable stuff, like song name and its genre
feed_back_cols = [Track_id, Song_name, 'genre']
feed_back = df_songs[feed_back_cols]
# feed_back # print out the feedback dataframe to check

# Setting up the KNN model

knn = NearestNeighbors(n_neighbors = 10, metric = "cosine")
knn.fit(X_scaled)

# to be updated
dist, ind = knn.kneighbors(X_scaled)

# Finding the index of a track id and reverse
meta_cols = [c for c in [Track_id, Song_name] if c is not None]
meta = df_songs[meta_cols]

trackid_to_index = {trackid : i for i, trackid in enumerate(df_songs[Track_id].values)}
index_to_trackid = np.array(df_songs[Track_id].values)

# Recommender:
# A function with inputs:
# seed_id, k

# Search by ID
def recommender_by_seed_id(seed_id, k):
  index = trackid_to_index[seed_id]
  distances, indices = knn.kneighbors(X_scaled[index : index + 1], n_neighbors = min(k+1, len(df_songs)))
  recommended_indecies = [i for i in indices[0] if i != index][:k]
  return df_songs.iloc[recommended_indecies][[Track_id, Song_name, 'genre']]

# Search by name
def recommender_by_name(seed_name, k):
  if Song_name not in df_songs.columns:
    raise ValueError("No song name on record")


  the_song = df_songs[df_songs[Song_name].str.lower() == str(seed_name).lower()]

  if the_song.empty:
    raise ValueError("Seed song not found.")
  seed_id = the_song.iloc[0][Track_id]

  return recommender_by_seed_id(seed_id, k)

# Search by Feature
def recommender_by_features(user_features_dict, k=10):
# Takes user input, fills missing features with dataset averages,
# scales the data, and finds nearest songs."

    input_vector = df_songs[feature_cols].mean() # Create a vector with the
                                                  # average values of the dataset

    for feature, value in user_features_dict.items(): # Update with
                                                      # user's specific inputs
        if feature in feature_cols:
            input_vector[feature] = value

    input_df = pd.DataFrame([input_vector], columns=feature_cols) # Convert to dataframe for the scaler

    input_scaled = scaler.transform(input_df) # Convert to dataframe for the scaler

    distances, indices = knn.kneighbors(input_scaled, n_neighbors=k) # Find neighbors

    return df_songs.iloc[indices[0]][[Track_id, Song_name, 'genre']] # results

def get_valid_input(prompt): # user can only enter floats in designed range
    """Ensures user enters a float between 0.0 and 1.0"""
    while True:
        try:
            value = float(input(prompt))
            if 0.0 <= value <= 1.0:
                return value
            print("  -> Please enter a number between 0.0 and 1.0.")
        except ValueError:
            print("  -> Invalid input. Please enter a number.")

def better_looking_results(recommendations_df): # print out result better
    print("\n" + "-"*50)
    print(f"{'#':<4} {'Song Name':<30} {'Genre':<15}")
    print("-"*50)

    counter = 1

    for index, row in recommendations_df.iterrows():
        name = row[Song_name]
        genre = row['genre']

        display_name = (name[:27] + '..') if len(name) > 27 else name

        print(f"{counter:<4} {display_name:<30} {genre:<15} ")
        counter += 1
    print("-"*50 + "\n")

def main(): # User Interaction

    print("Welcome to the Spotify Recommender!")

# While-True loop
    while True:
        print("\n" + "="*40) # 分割线
        user_chosen_function = input(
            "How would you like to look for songs? \n"
            "  A: Enter Seed Song Name\n"
            "  B: Enter Song Characteristics (Mood/Energy)\n"
            "  Q: Quit\n"
            "Your input: ").strip().lower()

        if user_chosen_function == "q":
            print("\nGoodbye! Happy listening.")
            break # stop the loop

        # OPTION A: Search by Name
        elif user_chosen_function == "a":
            seed_song = input("Enter a song name: ")
            try: # using try-except here so no ugly err warnings lol
                print(f"\nSearching based on '{seed_song}'...")
                recommendations = recommender_by_name(seed_song, 10)
                better_looking_results(recommendations)
            except ValueError as Bruh:
                print(f"\nError: {Bruh}")
            except IndexError: # No such song
                print("\nError: Song not found in database.")

        # OPTION B: Search by Features
        elif user_chosen_function == "b":
            print("\n=== Enter values (0.0 = Low, 1.0 = High) ===")

            # We ask for specific inputs using the helper function
            song_energy = get_valid_input("Energy (Intensity): ")
            song_dance = get_valid_input("Danceability: ")
            song_valence = get_valid_input("Valence (Mood: 0=Sad, 1=Happy): ")
            song_acoustic = get_valid_input("Acousticness: ")

            user_inputs = {
                'energy': song_energy,
                'danceability': song_dance,
                'valence': song_valence,
                'acousticness': song_acoustic
            }

            print("\nFinding songs with matching characteristics...")
            recommendations = recommender_by_features(user_inputs, 10)
            better_looking_results(recommendations)

        # INVALID INPUT
        else:
            print("\nInvalid input. Please type A, B, or Q.")

# Run the program
main()

"""**A Small "Read Me":**

**Key functions:**

track_id / song name to row number, location identifying
- Given a track id, what row number is it in?
- Given a row number, which track ID does it represent?
give back a result table (song name, genre, time in s)

**Future Improvements:**

- Add functions such as recommending songs based on specific feature of the song, such as dancebility. (Almost done)
- Exclude the seed through data clean up.
- Find recommendations by multiple seeds.
- User feedback and product improvement
- GUI
- Recommendation based on Genre (label needed)
- figure out file path so everyone can use it without mounting to google drive which creates errors due to absent of file path

**Log 2025 NOV 3**

*  track id --> index tracing done.
*   Built rec by id and rec by name.

*   worked on excluding seed's appearance due to repetition in datasheet.
"""